# Generated by Django 5.2 on 2025-04-26 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='biography',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(choices=[('France', 'France'), ('Espagne', 'Espagne'), ('Japon', 'Japon'), ('Corée du sud', 'Coree Du Sud'), ('Étas-Unis', 'Usa'), ('Mexique', 'Mexique'), ('Autre', 'Autre')], default='France', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='official_homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='year_created',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
