# Generated by Django 5.2 on 2025-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_brand_active_brand_biography_brand_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(choices=[('France', 'France'), ('Espagne', 'Espagne'), ('Japon', 'Japon'), ('Corée du sud', 'Coree Du Sud'), ('Étas-Unis', 'Usa'), ('Mexique', 'Mexique'), ('Autre', 'Autre')], max_length=100),
        ),
    ]
