# Generated by Django 5.2 on 2025-04-26 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_brand_creator_alter_brand_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='type',
            field=models.CharField(choices=[('Vêtement', 'Vêtement'), ('Chaussure', 'Chaussure'), ('Poster', 'Poster'), ('Divers', 'Divers')], default='Divers', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='year',
            field=models.IntegerField(default=2005, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
