# Generated by Django 5.2 on 2025-04-28 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_brand_sold_brand_type_brand_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('sold', models.BooleanField(default=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2024)])),
                ('type', models.CharField(choices=[('Vêtement', 'Vêtement'), ('Chaussure', 'Chaussure'), ('Poster', 'Poster'), ('Divers', 'Divers')], max_length=100)),
            ],
        ),
    ]
