# Generated by Django 5.2 on 2025-04-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='type',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='year',
        ),
    ]
