# Generated by Django 5.2 on 2025-04-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_brand_sold_remove_brand_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.brand'),
        ),
    ]
