# Generated by Django 5.2 on 2025-04-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='like_new',
            field=models.BooleanField(default=False),
        ),
    ]
