# Generated by Django 5.2 on 2025-04-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_brand_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='like_new',
        ),
    ]
